clear;
clc;

addpath(genpath(pwd))

Result1 = platemo('-algorithm', @NSGAII, ...
        '-problem', @DTLZ2, ...
        '-M', 3, ...
        '-N', 92);

Result2 = platemo('-algorithm', @NSGAIII, ...
                 '-problem', @DTLZ2, ...
                 '-M', 3, ...
                 '-N', 92);

save('nsga3_result.mat', 'Result1');

save('nsga2_result.mat', 'Result2');
