clear;
clc;

addpath(genpath(pwd))

%% ZDT1

[~, Obj1, ~] = platemo( ...
    'algorithm', @NSGAII, ...
    'problem', @ZDT1, ...
    'N', 100 ...
);

[~, Obj2, ~] = platemo( ...
    'algorithm', @NSGAIII, ...
    'problem', @ZDT1, ...
    'N', 100 ...
);

save('zdt1_nsga2.mat', 'Obj1');
save('zdt1_nsga3.mat', 'Obj2');