clear;
clc;

addpath(genpath(pwd))

%% WFG1

[~, Obj1, ~] = platemo( ...
    'algorithm', @NSGAII, ...
    'problem', @WFG2, ...
    'M', 3, ...
    'N', 92 ...
);

[~, Obj2, ~] = platemo( ...
    'algorithm', @NSGAIII, ...
    'problem', @WFG2, ...
    'M', 3, ...
    'N', 92 ...
);

save('wfg2_nsga2.mat', 'Obj1');
save('wfg2_nsga3.mat', 'Obj2');